services:
  fcgi:
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      backend:
    # Явно указываем hostname для корректного разрешения имени
    hostname: fcgi

  httpd:
    image: "httpd:2.4.62"
    ports:
      - "8080:80"
    volumes:
      - "./httpd.conf:/usr/local/apache2/conf/httpd.conf"
      - "./static:/var/www"
    networks:
      backend:
    # Добавляем зависимость
    depends_on:
      - fcgi

networks:
  backend: